### PR TITLE
Improvements to error handling.

### PR DESCRIPTION
**Pull request by cscott**
Make sure we always clean up our temp dir, and give the user the ability to specify where it should be located.

Always report errors via the callback.

### CODE REVIEW

**Comment by rolfn** [comment]
In addition: I would like to have a switch (e.g. "keep:true") to indicate that the temp dir will not be removed after the LaTeX run (for debugging).

**Comment by cscott** [comment]
@rolfn separate patch, i think.  although i agree that would be useful.  but let's get this merged first!

@gammasoft ping!  this pull request is seven months old now.  i'd like to be able to use the upstream package instead of my own fork.

**Comment by renatoargh** [comment]
@cscott can you please check if `npm install gammalatex` installs version `0.0.7` and if this version contains all you need? thanks

**Comment by cscott** [comment]
Looks good to me.  Thanks!

**Pull request merged**
